### ISSUE TITLE
Add the multimodal generation/reconstruction block using the diffusion model

### ISSUE THREAD

**Issue by Benny0323** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#16]
Dear authors, could you add the multimodal generation/reconstruction block using the diffusion model at your convenience?
And I also want to be a part of the contributor. THX!

**Comment by amirhossein-kz** [comment]
Hi @Benny0323, thanks for your suggestion! Feel free to submit a pull request with the multimodal generation/reconstruction block you'd like to contribute. Once it's reviewed, I’ll add you as a collaborator. Looking forward to your contribution!

**Comment by Benny0323** [comment]
OK! @amirhossein-kz
