### ISSUE TITLE
Correction for Publication Information of "Meddiffusion"

### ISSUE THREAD

**Issue by 0606zt** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#19]
I just want to say that the literature you compiled has been incredibly helpful for my research. Thank you for your hard work!

I noticed a small error regarding the publication information for the paper titled "Meddiffusion: Boosting Health Risk Prediction via Diffusion-Based Data Augmentation." It should be published in SIAM 2024 instead of MICCAI 2023. Thank you for your attention to this detail!

**Comment by amirhossein-kz** [comment]
Hi @0606zt,

Thank you so much for your interest in our repository. I'm glad it was helpful for your research.
The issue has been fixed now. Thanks for letting us know. Have a great holiday! 😊
