### ISSUE TITLE
Request for Paper Update

### ISSUE THREAD

**Issue by CKBling** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#20]
I would like to kindly request an update to include the following paper, which has been accepted to MICCAI 2024:

**Title**: Slice-Consistent 3D Volumetric Brain CT-to-MRI Translation with 2D Brownian Bridge Diffusion Model
**Authors**: Kyobin Choo, Youngjun Jun, Mijin Yun, Seong Jae Hwang
**ArXiv Link**: https://arxiv.org/abs/2407.05059

This paper presents a method that utilizes a 2D diffusion model to achieve 3D volume-to-volume translation, marking a significant first in the field.

Thank you very much for your attention to this matter.

**Comment by amirhossein-kz** [comment]
Hi @CKBling ,

Thank you for your suggestion! The paper has been added to the repository. 

Congratulations on your MICCAI 2024 acceptance! Have a great holiday! 😊
