### ISSUE TITLE
The github link for that paper seems to be incorrect.

### ISSUE THREAD

**Issue by ArtistDeveloper** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#4]
This is the last paper in the Image Generation category.

Three-Dimensional Medical Image Synthesis with Denoising Diffusion Probabilistic Models
Zolnamar Dorjsembe, Sodtavilan Odonchimed, Furen Xiao
[22nd Apr., 2022] [MIDL, 2022]
[[Paper](https://openreview.net/pdf?id=Oz7lKWVh45H)] [[Github](https://github.com/torchddm/ddm)]

The GitHub link for the above paper is [here](https://github.com/DL-Circle/3D-DDPM), and it is not yet publicly available.

**Comment by amirhossein-kz** [comment]
Hi @ArtistDeveloper,
Thank you very much for your attention. It is fixed now. Thanks!
