### ISSUE TITLE
can you update?

### ISSUE THREAD

**Issue by xiaoiker** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#5]
Thanks for the great efforts.

Can you update the information of paper, Generating Realistic 3D Brain MRIs Using a Conditional Diffusion Probabilistic Model, it is accepted by MICCAI 2023. Thanks a lot~

**Comment by amirhossein-kz** [comment]
Hi @xiaoiker,
Thanks for your interest! Congratulations on your acceptance and excellent paper. It is now updated.
