### ISSUE TITLE
Add CVPRW 2023

### ISSUE THREAD

**Issue by alvarogonjim** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#6]
Hi! Thanks for the collection of amazing papers.

Is it possible to add the following article to the list:

**SANO: Score-Based Diffusion Model for Anomaly Localization in Dermatology**
_Alvaro Gonzalez-Jimenez, Simone Lionetti, Marc Pouly, Alexander A. Navarini_
[18th Jun., 2023] [CVPR Workshop, 2023]
[[Paper](https://openaccess.thecvf.com/content/CVPR2023W/VAND/html/Gonzalez-Jimenez_SANO_Score-Based_Diffusion_Model_for_Anomaly_Localization_in_Dermatology_CVPRW_2023_paper.html)]

**Comment by amirhossein-kz** [comment]
Hi @alvarogonjim,
Thank you so much for your interest and congrats on your amazing paper! It is now added! 
Thanks!
