### ISSUE TITLE
Add a new survey paper on tabular/time series data

### ISSUE THREAD

**Issue by heejkoo1** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#7]
Hello, can you kindly add our new survey paper on tabular/time series data? Its information is as follows:

A Comprehensive Survey on Generative Diffusion Models for Structured Data
Heejoon Koo, To Eun Kim
arXiv 2023. [[Paper](https://arxiv.org/abs/2306.04139)]
7 Jun 2023

Thank you,
Heejoon

**Comment by amirhossein-kz** [comment]
Hi @heejkoo1,
Thank you for your interest in our repo. It has been included now. Thanks!
