### ISSUE TITLE
CVPR23 paper with released code

### ISSUE THREAD

**Issue by ISCANCHU** [amirhossein-kz/Awesome-Diffusion-Models-in-Medical-Imaging#9]
Hello, 

Can you kindly add our work published in CVPR23? We have released the code on Github.

Its information is as follows:

BBDM: Image-to-image Translation with Brownian Bridge Diffusion Models, Bo Li, Kaitao Xue, Bin Liu, Yu-Kun Lai, 2023 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), Vancouver, BC, Canada, 2023, pp. 1952-1961
Code: https://github.com/xuekt98/BBDM

Best regards
Bo

**Comment by amirhossein-kz** [comment]
Hi @ISCANCHU ,

Thank you for your interest in our repo, and congratulations on your excellent paper! This repository is exclusively dedicated to medical imaging papers. If your work includes experiments related to medical cases, we would be delighted to include your paper. Thank you!
